name: test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    name: cljstyle-${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install cljstyle
        uses: ./
        with:
          version: 0.14.0

      - name: Run cljstyle
        run: cljstyle check src
